version: '3.7'
name: 'nginx_react_typescript_docker'

services:
  app:
    image: react-app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./nginx/nginx.conf://etc/nginx/nginx.conf:ro"